/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.zavaglia.advent2021;

import java.io.IOException;
import java.util.Arrays;

public class App {
    public static void main(String[] args) throws IOException {

        var questions = Arrays.asList(
                new Question01()
        );

        for (var q : questions) {
            System.out.println("** Question " + q.GetQuestionNumber());
            var a = q.A();
            if (a == q.ExpectedA()) {
                System.out.println("  A = " + a + " (PASSES)");
            } else {
                System.out.println("  A = " + a + "  (FAILS - expected " + q.ExpectedA() + ")");
            }
            var b = q.B();
            if (b == q.ExpectedB()) {
                System.out.println("  B = " + b + " (PASSES)");
            } else {
                System.out.println("  B = " + b + "  (FAILS - expected " + q.ExpectedB() + ")");
            }
        }

    }

    public String getGreeting() {
        return "Hello World!";
    }
}
